ReplicaNumber: 1

containers:
  containerPort: 8080
  image: 'quay.io/leomrg861/first-app'
  tag: 'chart_v1'

service:
  servicePort: 8080

probes:
  readinessProbe:
    httpGet:
      path: /health/readiness
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1 
    failureThreshold: 3

  livenessProbe:
    httpGet:
      path: /health/liveness
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1 
    failureThreshold: 3

volume:
  mount:
    path: /tmp/html
